from __future__ import annotations

import re
from pathlib import Path
from typing import Callable, Sequence

import cv2
import pandas as pd

SUPPORTED_FRAME_POSITIONS = ("start", "middle", "end")


def _safe_filename(value: object) -> str:
    """Convert an identifier into a filesystem-safe token."""
    token = re.sub(r"[^a-zA-Z0-9_-]+", "_", str(value)).strip("_")
    return token or "unknown"


def get_sampling_timestamps(
    start_time: float,
    end_time: float,
    frame_positions: Sequence[str] = SUPPORTED_FRAME_POSITIONS,
    edge_margin_seconds: float = 0.25,
) -> dict[str, float]:
    """Return local video timestamps for representative scene frames.

    Start and end samples are moved slightly away from detected cuts to reduce
    the chance of capturing transitions, black frames, or motion blur. The
    effective margin is capped at 20% of scene duration so short scenes remain
    valid.
    """
    start_time = float(start_time)
    end_time = float(end_time)
    duration = end_time - start_time

    if duration <= 0:
        raise ValueError("Scene end time must be greater than start time.")

    requested_positions = tuple(dict.fromkeys(frame_positions))
    unsupported = set(requested_positions) - set(SUPPORTED_FRAME_POSITIONS)
    if unsupported:
        raise ValueError(f"Unsupported frame positions: {sorted(unsupported)}")
    if not requested_positions:
        raise ValueError("At least one frame position must be selected.")
    if edge_margin_seconds < 0:
        raise ValueError("edge_margin_seconds must be non-negative.")

    margin = min(float(edge_margin_seconds), duration * 0.20)
    candidates = {
        "start": start_time + margin,
        "middle": start_time + (duration / 2.0),
        "end": end_time - margin,
    }

    return {position: candidates[position] for position in requested_positions}


def _resize_frame(frame, max_width: int | None):
    """Resize a frame while preserving aspect ratio."""
    if not max_width or max_width <= 0:
        return frame

    height, width = frame.shape[:2]
    if width <= max_width:
        return frame

    scale = max_width / width
    new_size = (int(round(width * scale)), int(round(height * scale)))
    return cv2.resize(frame, new_size, interpolation=cv2.INTER_AREA)


def _read_frame_at_timestamp(cap: cv2.VideoCapture, timestamp_seconds: float):
    """Read one frame from an open video capture at a timestamp."""
    cap.set(cv2.CAP_PROP_POS_MSEC, float(timestamp_seconds) * 1000.0)
    success, frame = cap.read()
    return frame if success else None


def sample_frames_from_scenes(
    scenes: pd.DataFrame,
    output_dir: str | Path,
    frame_positions: Sequence[str] = SUPPORTED_FRAME_POSITIONS,
    edge_margin_seconds: float = 0.25,
    jpeg_quality: int = 85,
    max_width: int | None = None,
    overwrite: bool = False,
    progress_callback: Callable[[int, int, str], None] | None = None,
) -> pd.DataFrame:
    """Extract representative frames from a table of detected scenes.

    Parameters
    ----------
    scenes:
        Scene table generated by ``detect_scenes``.
    output_dir:
        Experiment-specific folder where JPEG files will be stored.
    frame_positions:
        Any combination of ``start``, ``middle``, and ``end``.
    edge_margin_seconds:
        Offset applied to start/end samples to avoid exact cut boundaries.
    jpeg_quality:
        JPEG encoding quality from 1 to 100.
    max_width:
        Optional maximum image width. ``None`` preserves source resolution.
    overwrite:
        Replace existing JPEG files when True; otherwise reuse them.
    progress_callback:
        Optional callback receiving ``current_scene, total_scenes, segment_id``.

    Returns
    -------
    pandas.DataFrame
        One row per requested frame, including timestamps, file path, status,
        image dimensions, and whether an existing file was reused.
    """
    required_columns = {
        "episode_id",
        "part_id",
        "segment_id",
        "video_path",
        "part_start_time",
        "part_end_time",
        "global_start_time",
        "duration",
    }
    missing = required_columns - set(scenes.columns)
    if missing:
        raise ValueError(f"Scene table is missing required columns: {sorted(missing)}")
    if scenes.empty:
        return pd.DataFrame()
    if not 1 <= int(jpeg_quality) <= 100:
        raise ValueError("jpeg_quality must be between 1 and 100.")

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    working = scenes.copy()
    working["duration"] = pd.to_numeric(working["duration"], errors="coerce")
    working = working.dropna(subset=["duration"])
    working = working[working["duration"] > 0].copy()
    working = working.sort_values(
        [column for column in ("part_order", "part_start_time") if column in working.columns]
    )

    total_scenes = len(working)
    rows: list[dict] = []
    completed_scenes = 0

    for video_path_value, group in working.groupby("video_path", sort=False):
        video_path = Path(str(video_path_value))
        cap = cv2.VideoCapture(str(video_path))
        capture_open = video_path.exists() and cap.isOpened()
        fps = float(cap.get(cv2.CAP_PROP_FPS) or 0.0) if capture_open else 0.0

        for _, scene in group.iterrows():
            episode_id = str(scene["episode_id"])
            part_id = str(scene["part_id"])
            segment_id = str(scene["segment_id"])
            part_start = float(scene["part_start_time"])
            part_end = float(scene["part_end_time"])
            global_start = float(scene["global_start_time"])
            segment_duration = float(scene["duration"])

            try:
                timestamps = get_sampling_timestamps(
                    start_time=part_start,
                    end_time=part_end,
                    frame_positions=frame_positions,
                    edge_margin_seconds=edge_margin_seconds,
                )
            except ValueError as exc:
                timestamps = {}
                rows.append(
                    {
                        "episode_id": episode_id,
                        "part_id": part_id,
                        "part_order": scene.get("part_order"),
                        "segment_id": segment_id,
                        "segment_duration": segment_duration,
                        "frame_position": None,
                        "frame_path": None,
                        "source_video_path": str(video_path),
                        "part_timestamp_seconds": None,
                        "global_timestamp_seconds": None,
                        "sample_offset_seconds": None,
                        "source_frame_index": None,
                        "image_width": None,
                        "image_height": None,
                        "file_size_bytes": None,
                        "success": False,
                        "reused_existing": False,
                        "error": str(exc),
                    }
                )

            frame_dir = output_dir / _safe_filename(episode_id) / _safe_filename(part_id)
            frame_dir.mkdir(parents=True, exist_ok=True)

            for frame_position, part_timestamp in timestamps.items():
                sample_offset = part_timestamp - part_start
                global_timestamp = global_start + sample_offset
                frame_filename = f"{_safe_filename(segment_id)}_{frame_position}.jpg"
                frame_path = frame_dir / frame_filename
                source_frame_index = int(round(part_timestamp * fps)) if fps > 0 else None

                row = {
                    "episode_id": episode_id,
                    "part_id": part_id,
                    "part_order": scene.get("part_order"),
                    "segment_id": segment_id,
                    "segment_duration": segment_duration,
                    "frame_position": frame_position,
                    "frame_path": str(frame_path),
                    "source_video_path": str(video_path),
                    "part_timestamp_seconds": part_timestamp,
                    "global_timestamp_seconds": global_timestamp,
                    "sample_offset_seconds": sample_offset,
                    "source_frame_index": source_frame_index,
                    "image_width": None,
                    "image_height": None,
                    "file_size_bytes": None,
                    "success": False,
                    "reused_existing": False,
                    "error": None,
                }

                if frame_path.exists() and not overwrite:
                    row.update(
                        {
                            "success": True,
                            "reused_existing": True,
                            "file_size_bytes": frame_path.stat().st_size,
                        }
                    )
                    rows.append(row)
                    continue

                if not capture_open:
                    row["frame_path"] = None
                    row["error"] = (
                        "source_video_not_found" if not video_path.exists() else "could_not_open_video"
                    )
                    rows.append(row)
                    continue

                frame = _read_frame_at_timestamp(cap, part_timestamp)
                if frame is None:
                    row["frame_path"] = None
                    row["error"] = "could_not_read_frame"
                    rows.append(row)
                    continue

                frame = _resize_frame(frame, max_width=max_width)
                image_height, image_width = frame.shape[:2]
                write_params = [int(cv2.IMWRITE_JPEG_QUALITY), int(jpeg_quality)]
                write_success = bool(cv2.imwrite(str(frame_path), frame, write_params))

                if write_success:
                    row.update(
                        {
                            "success": True,
                            "image_width": int(image_width),
                            "image_height": int(image_height),
                            "file_size_bytes": frame_path.stat().st_size,
                        }
                    )
                else:
                    row["frame_path"] = None
                    row["error"] = "could_not_write_frame"

                rows.append(row)

            completed_scenes += 1
            if progress_callback is not None:
                progress_callback(completed_scenes, total_scenes, segment_id)

        cap.release()

    return pd.DataFrame(rows)
